name: Unit test for Lambda backend service

on:
  workflow_dispatch:
  push:
    branches:
    - main

env: 
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-1'
  SOURCE_DIR: 'website'
  DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
  PYTHON_VERSION: 3.11
  BACKEND_PATH: infra/

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage flake8 moto boto3
      - name: Run flake8 linter for Python
        run: |
          flake8 ${{ env.BACKEND_PATH }} --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ${{ env.BACKEND_PATH }} --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest with coverage report
        run: |
          pytest -vvv --capture=tee-sys --cov=${{ env.BACKEND_PATH }}